### ISSUE TITLE
ocli does not compile with gpsd >= 3.20 

### ISSUE THREAD

**Issue by mnhauke** [owntracks/ocli#9]
```
$ make
cc -Wall -Werror -Os -I/usr/local/include   -c -o owntracks-cli-publisher.o owntracks-cli-publisher.c
owntracks-cli-publisher.c: In function 'print_fix':
owntracks-cli-publisher.c:267:2: error: implicit declaration of function 'unix_to_iso8601'; did you mean 'now_to_iso8601'? [-Werror=implicit-function-declaration]
  267 |  unix_to_iso8601(ttime, tbuf, sizeof(tbuf));
      |  ^~~~~~~~~~~~~~~
      |  now_to_iso8601
owntracks-cli-publisher.c: In function 'conditionally_log_fix':
owntracks-cli-publisher.c:450:13: error: incompatible types when assigning to type 'double' from type 'timespec_t' {aka 'struct timespec'}
  450 |  int_time = fix->time;
      |             ^~~
cc1: all warnings being treated as errors
make: *** [<builtin>: owntracks-cli-publisher.o] Error 1
```

it seems unix_to_iso8601() is not longer available in recent gpsd versions....
https://gitlab.com/gpsd/gpsd/-/commit/095b023b5367ae0efe15e0d69f9a3f4de41396b8

**Comment by jpmens** [comment]
Thanks for reporting this. Would you be prepared to create a pull request to fix this?

**Comment by jpmens** [comment]
Fixed in https://github.com/owntracks/ocli/pull/10
